### ISSUE TITLE
KBQA files not provided

### ISSUE THREAD

**Issue by rnjtsh** [JBoRu/StructGPT#2]
Hi @JBoRu ,

I am trying to run the code for KBQA, but it seems the files for the WebQSP (processed data. pickle and npy file) are missing and there is no instruction provided on how to test for KBQA. May I request you update the KBQA?

--kg_source_path ./data/webqsp/subgraph_2hop_triples.npy \
--ent_type_path ./data/webqsp/ent_type_ary.npy \
--ent2id_path ./data/webqsp/ent2id.pickle \
--rel2id_path ./data/webqsp/rel2id.pickle \
--ent2name_path ./data/webqsp/entity_name.pickle \

**Comment by JBoRu** [comment]
Hi,
   Thanks for your attention. I will upload the dataset of WebQSP to Google Drive immediately. The size of the processed data is a little big. Please wait patiently.

Best,
Jinhao
