### ISSUE TITLE
Can you share the `prompt` to query ChatGPT on `WTQ`?

### ISSUE THREAD

**Issue by Leolty** [JBoRu/StructGPT#3]
Hi there,

Thanks a lot for your amazing work. 

As titled, just curious about how to make ChatGPT follow the parsable output format.

**Comment by JBoRu** [comment]
You can directly use the final prompt [here](https://github.com/JBoRu/StructGPT/blob/4bd220a656cc479f72eb0263f0c949fb642b7f8e/prompts/prompt_for_wtq.json#LL6C25-L6C25).

**Comment by Leolty** [comment]
OK Thanks, so for the baseline (direct prompting), you did not ask ChatGPT to do CoT?

**Comment by JBoRu** [comment]
Yes!
