### ISSUE TITLE
是否支持中文？能否根据一组数据，用自然语言描述数据趋势？

### ISSUE THREAD

**Issue by fc13240** [JBoRu/StructGPT#4]
<img width="675" alt="weather" src="https://github.com/JBoRu/StructGPT/assets/5786628/396937ab-59c9-4467-be75-aa3ca1fe6701">
例如

1.描述一下图中温度的变化趋势，几日至几日温度将大幅上升,略有上升，还是基本持平；
2.描述一下图中天气的变化趋势，共有几天会出现降水，重点描述有哪几天连续降水（忽略小于等于两天的趋势）
3.描述一下图中风力的变化趋势，当风力大于等于4级视为风力较大，找出共有几日风力较大，以及连续大风的日期

**Comment by JBoRu** [comment]
感谢关注。理论上只要大模型支持中文的理解与回复，我们这套框架就可以适配。您只需要将相关表数据按照合适的序列化方法输入大模型。您可以尝试一下！

**Comment by fc13240** [comment]
合适的序列化方法是指？有参考格式吗？

**Comment by JBoRu** [comment]
本质上您给定的是一个天气相关的表，您可以按照论文里面对表的序列化方法进行序列化。
