### ISSUE TITLE
Access Freebase KG

### ISSUE THREAD

**Issue by the-anonymous-bs** [JBoRu/StructGPT#5]
Hi. Thanks for the great work! 

I have opened various preprocessed data for webQSP, but I still did not understand how to map from freebase mid to entity name string. I wonder if you could provide some instructions on how I should use files like "ent2id.pickle", "subgraph_2hop_triples.npy" and "entity_name.pickle". Especially if I want to find related triplets for each question in the test set, how should I do this?

**Comment by JBoRu** [comment]
Hi,
   Thanks for your attention. I would update the detailed operations about how to preprocess these data as soon as possible.
